services:
  api:
    container_name: next_web_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production 
      - API_URL=http://localhost:8000
      - API_URL2=http://192.168.0.128:8000
      - HOST=0.0.0.0
    restart: always