services:
  api:
    container_name: nest_backend_dev
    image: node:24-alpine
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      CLIENT_URL: ${CLIENT_URL}
      CLIENT_URL_2: ${CLIENT_URL_2}
      CLIENT_URL_3: ${CLIENT_URL_3}
      CLIENT_URL_4: ${CLIENT_URL_4}
      ADMIN_URL: ${ADMIN_URL}

      TTL_ACCESS_TOKEN: ${TTL_ACCESS_TOKEN}
      TTL_REFRESH_TOKEN: ${TTL_REFRESH_TOKEN}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}

      DATABASE_URL: ${DATABASE_URL}
      
      SECRET_JWT: ${SECRET_JWT}

    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "corepack enable && pnpm install && pnpm dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
  
networks:
  app-network:
    driver: brdge